# IP1
## Noah Clark
### v 1.0
#### DS-160-02

In [1]:
import numpy as np

In [17]:
array2d=np.array([[10, 20], [30, 40]])
print(array2d)

print(array2d**2)

print(array2d + 100)

print(array2d*5)

print(array2d**0.5)

[[10 20]
 [30 40]]
[[ 100  400]
 [ 900 1600]]
[[110 120]
 [130 140]]
[[ 50 100]
 [150 200]]
[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


In [20]:
array1=np.array([[[3, 6, 9], [12, 15, 18], [21, 24, 27]]])
array2=np.array([[[11, 12, 13], [14, 15, 16], [17, 18, 19]]])
np.multiply(array1, array2)

array([[[ 33,  72, 117],
        [168, 225, 288],
        [357, 432, 513]]])

In [36]:
npy1=np.load("process1.npy")

npy2=np.load("process2.npy")

npy3=np.load("process3.npy")

npy4=np.load("process4.npy")

npy5=np.load("process5.npy")

In [41]:
npyarray=np.vstack(((((npy1, npy2, npy3, npy4, npy5)))))
print(npyarray)
npyarray.mean()

[[52 12 81  0 58]
 [96  4 61 16 43]
 [38 96 45 17 58]
 [97 21 22 25  6]
 [77  6 19  2 74]]


41.04